/*
AnyVisibleConverter.cs

This file is part of Morgan's CLR Advanced Runtime (MCART)

Author(s):
     César Andrés Morgan <xds_xps_ivx@hotmail.com>

Released under the MIT License (MIT)
Copyright © 2011 - 2026 César Andrés Morgan

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
of the Software, and to permit persons to whom the Software is furnished to do
so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

using System.Globalization;
using System.Windows;
using System.Windows.Data;

namespace TheXDS.MCART.ValueConverters;

/// <summary>
/// Determines a visibility value based on at least one value equal to
/// <see cref="Visibility.Visible"/>.
/// </summary>
public sealed class AnyVisibleConverter : IMultiValueConverter
{
    /// <summary>
    /// Determines a visibility value based on at least one value equal to
    /// <see cref="Visibility.Visible"/>.
    /// </summary>
    /// <param name="values">
    /// Values generated by the binding sources.
    /// </param>
    /// <param name="targetType">
    /// The type of the target binding property.
    /// </param>
    /// <param name="parameter">
    /// Converter parameter that will be used.
    /// </param>
    /// <param name="culture">
    /// Culture reference that will be used in the converter.
    /// </param>
    /// <returns>
    /// <see cref="Visibility.Visible"/> if at least one of the values
    /// is <see cref="Visibility.Visible"/>, otherwise
    /// <see cref="Visibility.Collapsed"/>.
    /// </returns>
    public object Convert(object[] values, Type targetType, object parameter, CultureInfo culture)
    {
        return values.OfType<Visibility>().Any(p => p == Visibility.Visible)
            ? Visibility.Visible
            : Visibility.Collapsed;
    }

    /// <summary>
    /// Implements <see cref="IMultiValueConverter.ConvertBack"/>.
    /// </summary>
    /// <param name="value">Object to convert.</param>
    /// <param name="targetTypes">Types of the target bindings.</param>
    /// <param name="parameter">
    /// Converter parameter that will be used.
    /// </param>
    /// <param name="culture">
    /// Culture used for the conversion.
    /// </param>
    /// <returns>
    /// This method always throws an <see cref="InvalidOperationException"/>.
    /// </returns>
    /// <exception cref="InvalidOperationException">
    /// This method always throws this exception when called.
    /// </exception>
    public object[] ConvertBack(object value, Type[] targetTypes, object parameter, CultureInfo culture)
    {
        throw new InvalidOperationException();
    }
}
