/*
BooleanToBlurEffectConverter.cs

This file is part of Morgan's CLR Advanced Runtime (MCART)

Author(s):
     César Andrés Morgan <xds_xps_ivx@hotmail.com>

Released under the MIT License (MIT)
Copyright © 2011 - 2026 César Andrés Morgan

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
of the Software, and to permit persons to whom the Software is furnished to do
so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

using System.Globalization;
using System.Windows.Data;
using System.Windows.Media.Effects;
using TheXDS.MCART.Resources;

namespace TheXDS.MCART.ValueConverters;

/// <summary>
/// Genera un efecto de desenfoque basado en una condición booleana.
/// </summary>
public sealed class BooleanToBlurEffectConverter : IValueConverter
{
    /// <summary>
    /// Generates a blur effect based on a boolean condition.
    /// </summary>
    /// <param name="value">
    /// The value generated by the binding source.
    /// </param>
    /// <param name="targetType">
    /// The type of the target binding property.
    /// </param>
    /// <param name="parameter">
    /// The converter parameter to use.
    /// </param>
    /// <param name="culture">
    /// The culture to use in the converter.
    /// </param>
    /// <returns>
    /// An object of type <see cref="BlurEffect"/> that can be applied to a
    /// <see cref="System.Windows.UIElement"/>, or <see langword="null"/> if
    /// the <paramref name="parameter"/> is not a boolean value.
    /// </returns>
    public object? Convert(object? value, Type targetType, object? parameter, CultureInfo culture)
    {
        double TryConvert()
        {
            try
            {
                return (double)System.Convert.ChangeType(parameter, typeof(double));
            }
            catch
            {
                return 5.0;
            }
        }

        return value is bool b && b ? new BlurEffect
        {
            Radius = parameter switch
            {
                null => 5.0,
                string s => double.TryParse(s, out double r) ? r : throw Errors.InvalidValue(nameof(parameter), parameter),
                _ => TryConvert()
            }
        } : null;
    }

    /// <summary>
    /// Generates a blur effect based on a boolean condition.
    /// </summary>
    /// <param name="value">
    /// The value generated by the binding source.
    /// </param>
    /// <param name="targetType">
    /// The type of the target binding property.
    /// </param>
    /// <param name="parameter">
    /// The converter parameter to use.
    /// </param>
    /// <param name="culture">
    /// The culture to use in the converter.
    /// </param>
    /// <returns>
    /// An object of type <see cref="BlurEffect"/> that can be applied to a
    /// <see cref="System.Windows.UIElement"/>.
    /// </returns>
    public object Convert(bool value, Type targetType, object? parameter, CultureInfo culture)
    {
        return Convert((object)value, targetType, parameter, culture)!;
    }

    /// <summary>
    /// Implements <see cref="IValueConverter.ConvertBack"/>.
    /// </summary>
    /// <param name="value">The object to convert.</param>
    /// <returns>
    /// <see langword="true"/> if the value is a <see cref="BlurEffect"/>,
    /// otherwise <see langword="false"/>.
    /// </returns>
    public bool ConvertBack(object value)
    {
        return value is BlurEffect;
    }

    object IValueConverter.ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
    {
        return ConvertBack(value);
    }
}
