//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheXDS.MCART.Wpf.PluginSupport.Legacy.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheXDS.MCART.Wpf.PluginSupport.Legacy.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ensamblado.
        /// </summary>
        public static string Assembly {
            get {
                return ResourceManager.GetString("Assembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Beta.
        /// </summary>
        public static string Beta {
            get {
                return ResourceManager.GetString("Beta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Compatibilidad.
        /// </summary>
        public static string Compatibility {
            get {
                return ResourceManager.GetString("Compatibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Copyright.
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Interacciones.
        /// </summary>
        public static string Interactions {
            get {
                return ResourceManager.GetString("Interactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Interfaz.
        /// </summary>
        public static string Interface {
            get {
                return ResourceManager.GetString("Interface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Interfaces.
        /// </summary>
        public static string Interfaces {
            get {
                return ResourceManager.GetString("Interfaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Etiqueta.
        /// </summary>
        public static string Label {
            get {
                return ResourceManager.GetString("Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Licencia.
        /// </summary>
        public static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Versión mínima de MCART.
        /// </summary>
        public static string MinMcartVersion {
            get {
                return ResourceManager.GetString("MinMcartVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Espacio de nombres.
        /// </summary>
        public static string Namespace {
            get {
                return ResourceManager.GetString("Namespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Explorador de plugins.
        /// </summary>
        public static string PluginBrowser {
            get {
                return ResourceManager.GetString("PluginBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Plugin soportado por MCART.
        /// </summary>
        public static string PluginSupportedByMcart {
            get {
                return ResourceManager.GetString("PluginSupportedByMcart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione un Plugin para continuar.
        /// </summary>
        public static string SlctAPlugin {
            get {
                return ResourceManager.GetString("SlctAPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Versión objetivo de MCART.
        /// </summary>
        public static string TgtMcartVersion {
            get {
                return ResourceManager.GetString("TgtMcartVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inestable.
        /// </summary>
        public static string Unstable {
            get {
                return ResourceManager.GetString("Unstable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Versión.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
