//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheXDS.MCART.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheXDS.MCART.Resources.Strings.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede escribir el objeto de tipo {0}..
        /// </summary>
        internal static string CantWriteObjOfT {
            get {
                return ResourceManager.GetString("CantWriteObjOfT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operación circular detectada..
        /// </summary>
        internal static string CircularOpDetected {
            get {
                return ResourceManager.GetString("CircularOpDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La clase especificada no es instanciable..
        /// </summary>
        internal static string ClassNotInstantiable {
            get {
                return ResourceManager.GetString("ClassNotInstantiable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La clase &apos;{0}&apos; no pudo ser instanciada con los parámetros de constructor especificados..
        /// </summary>
        internal static string ClassNotInstantiableWIthArgs {
            get {
                return ResourceManager.GetString("ClassNotInstantiableWIthArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La clase {0} no es instanciable..
        /// </summary>
        internal static string ClassXNotinstantiable {
            get {
                return ResourceManager.GetString("ClassXNotinstantiable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La colección no contiene elementos..
        /// </summary>
        internal static string EmptyCollection {
            get {
                return ResourceManager.GetString("EmptyCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se esperaba un tipo de colección enumerable..
        /// </summary>
        internal static string EnumerableTypeExpected {
            get {
                return ResourceManager.GetString("EnumerableTypeExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El tipo {0} no es un tipo de enumeración válido..
        /// </summary>
        internal static string EnumTypeExpected {
            get {
                return ResourceManager.GetString("EnumTypeExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha producido un error al intentar cargar el contenido de la licencia..
        /// </summary>
        internal static string ErrorLoadingLicense {
            get {
                return ResourceManager.GetString("ErrorLoadingLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ocurrido un error al cargar el recurso {0}..
        /// </summary>
        internal static string ErrorLoadingRes {
            get {
                return ResourceManager.GetString("ErrorLoadingRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El formato {0} no está soportado..
        /// </summary>
        internal static string FormatNotSupported {
            get {
                return ResourceManager.GetString("FormatNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El argumento {0} contiene un valor inválido en este contexto..
        /// </summary>
        internal static string InvalidArgument {
            get {
                return ResourceManager.GetString("InvalidArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El tipo no es válido en este contexto..
        /// </summary>
        internal static string InvalidType {
            get {
                return ResourceManager.GetString("InvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El URI apunta a un recurso no válido..
        /// </summary>
        internal static string InvalidUri {
            get {
                return ResourceManager.GetString("InvalidUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El valor proporcionado no es válido en este contexto..
        /// </summary>
        internal static string InvalidValue {
            get {
                return ResourceManager.GetString("InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El tipo {0} no es válido en este contexto..
        /// </summary>
        internal static string InvalidXType {
            get {
                return ResourceManager.GetString("InvalidXType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El URI que apunta al recurso &apos;{0}&apos; no es válido..
        /// </summary>
        internal static string InvalidXUri {
            get {
                return ResourceManager.GetString("InvalidXUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El valor {0} no es válido en este contexto..
        /// </summary>
        internal static string InvalidXValue {
            get {
                return ResourceManager.GetString("InvalidXValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  en {0}.
        /// </summary>
        internal static string InX {
            get {
                return ResourceManager.GetString("InX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El argumento mínimo debe ser inferior o igual al máximo..
        /// </summary>
        internal static string MinGtMax {
            get {
                return ResourceManager.GetString("MinGtMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La declaración del tipo {0} requiere un atributo de Guid..
        /// </summary>
        internal static string MissingGuidAttrFromType {
            get {
                return ResourceManager.GetString("MissingGuidAttrFromType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay información de pila disponible..
        /// </summary>
        internal static string NoStackInfo {
            get {
                return ResourceManager.GetString("NoStackInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El objeto está deshabilitado..
        /// </summary>
        internal static string ObjectIsDisabled {
            get {
                return ResourceManager.GetString("ObjectIsDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La propiedad &apos;{0}&apos; es de sólo lectura..
        /// </summary>
        internal static string PropIsReadOnly {
            get {
                return ResourceManager.GetString("PropIsReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La pila está vacía..
        /// </summary>
        internal static string StackUnderflow {
            get {
                return ResourceManager.GetString("StackUnderflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha detectado una manipulación inesperada de la aplicación, o la memoria del proceso ha sido corrompida. Detenga la ejecución del programa inmediatamente..
        /// </summary>
        internal static string TamperDetected {
            get {
                return ResourceManager.GetString("TamperDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El valor {0} está fuera del rango de valores definidos para la enumeración {1}..
        /// </summary>
        internal static string UndefinedEnum {
            get {
                return ResourceManager.GetString("UndefinedEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El valor debe estar entre {0} y {1}..
        /// </summary>
        internal static string ValueMustBeBetweenXandY {
            get {
                return ResourceManager.GetString("ValueMustBeBetweenXandY", resourceCulture);
            }
        }
    }
}
