//
//  generated.cs
//
//  This file has been generated by the Stetic GUI designer.
//
//  This program is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with this program.  If not, see <http://www.gnu.org/licenses/>.

namespace Stetic
{
    internal class Gui
    {
        private static bool initialized;
        internal static void Initialize(Gtk.Widget iconRenderer)
        {
            if (!initialized) initialized = true;
        }
    }
    internal class ActionGroups
    {
        public static Gtk.ActionGroup GetActionGroup(System.Type type) => GetActionGroup(type.FullName);
        public static Gtk.ActionGroup GetActionGroup(string name) => null;
    }
}