//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheXDS.MCART.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheXDS.MCART.Resources.Strings.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acerca de MCART....
        /// </summary>
        public static string AboutMCART {
            get {
                return ResourceManager.GetString("AboutMCART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bytes.
        /// </summary>
        public static string Bytes {
            get {
                return ResourceManager.GetString("Bytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EB.
        /// </summary>
        public static string EB {
            get {
                return ResourceManager.GetString("EB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exabytes.
        /// </summary>
        public static string EBl {
            get {
                return ResourceManager.GetString("EBl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EiB.
        /// </summary>
        public static string EiB {
            get {
                return ResourceManager.GetString("EiB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ebibytes.
        /// </summary>
        public static string EiBl {
            get {
                return ResourceManager.GetString("EiBl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GB.
        /// </summary>
        public static string GB {
            get {
                return ResourceManager.GetString("GB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gigabytes.
        /// </summary>
        public static string GBl {
            get {
                return ResourceManager.GetString("GBl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GiB.
        /// </summary>
        public static string GiB {
            get {
                return ResourceManager.GetString("GiB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gibibytes.
        /// </summary>
        public static string GiBl {
            get {
                return ResourceManager.GetString("GiBl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a KB.
        /// </summary>
        public static string KB {
            get {
                return ResourceManager.GetString("KB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Kilobytes.
        /// </summary>
        public static string KBl {
            get {
                return ResourceManager.GetString("KBl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a KiB.
        /// </summary>
        public static string KiB {
            get {
                return ResourceManager.GetString("KiB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Kibibytes.
        /// </summary>
        public static string KiBl {
            get {
                return ResourceManager.GetString("KiBl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La licencia no ha sido encontrada..
        /// </summary>
        public static string LicenseNotFound {
            get {
                return ResourceManager.GetString("LicenseNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MB.
        /// </summary>
        public static string MB {
            get {
                return ResourceManager.GetString("MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Megabytes.
        /// </summary>
        public static string MBl {
            get {
                return ResourceManager.GetString("MBl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MiB.
        /// </summary>
        public static string MiB {
            get {
                return ResourceManager.GetString("MiB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mebibytes.
        /// </summary>
        public static string MiBl {
            get {
                return ResourceManager.GetString("MiBl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sin contenido..
        /// </summary>
        public static string NoContent {
            get {
                return ResourceManager.GetString("NoContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sin licencia..
        /// </summary>
        public static string NoLicense {
            get {
                return ResourceManager.GetString("NoLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;nulo&gt;.
        /// </summary>
        public static string Null {
            get {
                return ResourceManager.GetString("Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PB.
        /// </summary>
        public static string PB {
            get {
                return ResourceManager.GetString("PB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Petabytes.
        /// </summary>
        public static string PBl {
            get {
                return ResourceManager.GetString("PBl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PiB.
        /// </summary>
        public static string PiB {
            get {
                return ResourceManager.GetString("PiB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pebibytes.
        /// </summary>
        public static string PiBl {
            get {
                return ResourceManager.GetString("PiBl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TB.
        /// </summary>
        public static string TB {
            get {
                return ResourceManager.GetString("TB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Terabytes.
        /// </summary>
        public static string TBl {
            get {
                return ResourceManager.GetString("TBl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TiB.
        /// </summary>
        public static string TiB {
            get {
                return ResourceManager.GetString("TiB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tebibytes.
        /// </summary>
        public static string TiBl {
            get {
                return ResourceManager.GetString("TiBl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha especificado una licencia, o la misma no ha sido incluída..
        /// </summary>
        public static string UnspecifiedLicense {
            get {
                return ResourceManager.GetString("UnspecifiedLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} días.
        /// </summary>
        public static string XDays {
            get {
                return ResourceManager.GetString("XDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} horas.
        /// </summary>
        public static string XHours {
            get {
                return ResourceManager.GetString("XHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} minutos.
        /// </summary>
        public static string XMinutes {
            get {
                return ResourceManager.GetString("XMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} segundos.
        /// </summary>
        public static string XSeconds {
            get {
                return ResourceManager.GetString("XSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a YB.
        /// </summary>
        public static string YB {
            get {
                return ResourceManager.GetString("YB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Yottabytes.
        /// </summary>
        public static string YBl {
            get {
                return ResourceManager.GetString("YBl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a YiB.
        /// </summary>
        public static string YiB {
            get {
                return ResourceManager.GetString("YiB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Yobibytes.
        /// </summary>
        public static string YiBl {
            get {
                return ResourceManager.GetString("YiBl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ZB.
        /// </summary>
        public static string ZB {
            get {
                return ResourceManager.GetString("ZB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Zettabytes.
        /// </summary>
        public static string ZBl {
            get {
                return ResourceManager.GetString("ZBl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ZiB.
        /// </summary>
        public static string ZiB {
            get {
                return ResourceManager.GetString("ZiB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Zebibytes.
        /// </summary>
        public static string ZiBl {
            get {
                return ResourceManager.GetString("ZiBl", resourceCulture);
            }
        }
    }
}
