//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheXDS.MCART.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheXDS.MCART.Resources.Strings.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acerca de MCART....
        /// </summary>
        public static string AboutMCART {
            get {
                return ResourceManager.GetString("AboutMCART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bytes.
        /// </summary>
        public static string Bytes {
            get {
                return ResourceManager.GetString("Bytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EB.
        /// </summary>
        public static string EB {
            get {
                return ResourceManager.GetString("EB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exabytes.
        /// </summary>
        public static string EBl {
            get {
                return ResourceManager.GetString("EBl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EiB.
        /// </summary>
        public static string EiB {
            get {
                return ResourceManager.GetString("EiB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ebibytes.
        /// </summary>
        public static string EiBl {
            get {
                return ResourceManager.GetString("EiBl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GB.
        /// </summary>
        public static string GB {
            get {
                return ResourceManager.GetString("GB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gigabytes.
        /// </summary>
        public static string GBl {
            get {
                return ResourceManager.GetString("GBl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GiB.
        /// </summary>
        public static string GiB {
            get {
                return ResourceManager.GetString("GiB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gibibytes.
        /// </summary>
        public static string GiBl {
            get {
                return ResourceManager.GetString("GiBl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KB.
        /// </summary>
        public static string KB {
            get {
                return ResourceManager.GetString("KB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilobytes.
        /// </summary>
        public static string KBl {
            get {
                return ResourceManager.GetString("KBl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KiB.
        /// </summary>
        public static string KiB {
            get {
                return ResourceManager.GetString("KiB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kibibytes.
        /// </summary>
        public static string KiBl {
            get {
                return ResourceManager.GetString("KiBl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La licencia no ha sido encontrada..
        /// </summary>
        public static string LicenseNotFound {
            get {
                return ResourceManager.GetString("LicenseNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar sesión.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB.
        /// </summary>
        public static string MB {
            get {
                return ResourceManager.GetString("MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Megabytes.
        /// </summary>
        public static string MBl {
            get {
                return ResourceManager.GetString("MBl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MiB.
        /// </summary>
        public static string MiB {
            get {
                return ResourceManager.GetString("MiB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mebibytes.
        /// </summary>
        public static string MiBl {
            get {
                return ResourceManager.GetString("MiBl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sin contenido..
        /// </summary>
        public static string NoContent {
            get {
                return ResourceManager.GetString("NoContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sin licencia..
        /// </summary>
        public static string NoLicense {
            get {
                return ResourceManager.GetString("NoLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;nulo&gt;.
        /// </summary>
        public static string Null {
            get {
                return ResourceManager.GetString("Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PB.
        /// </summary>
        public static string PB {
            get {
                return ResourceManager.GetString("PB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Petabytes.
        /// </summary>
        public static string PBl {
            get {
                return ResourceManager.GetString("PBl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PiB.
        /// </summary>
        public static string PiB {
            get {
                return ResourceManager.GetString("PiB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pebibytes.
        /// </summary>
        public static string PiBl {
            get {
                return ResourceManager.GetString("PiBl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TB.
        /// </summary>
        public static string TB {
            get {
                return ResourceManager.GetString("TB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terabytes.
        /// </summary>
        public static string TBl {
            get {
                return ResourceManager.GetString("TBl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TiB.
        /// </summary>
        public static string TiB {
            get {
                return ResourceManager.GetString("TiB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tebibytes.
        /// </summary>
        public static string TiBl {
            get {
                return ResourceManager.GetString("TiBl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha especificado una licencia, o la misma no ha sido incluída..
        /// </summary>
        public static string UnspecifiedLicense {
            get {
                return ResourceManager.GetString("UnspecifiedLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} días.
        /// </summary>
        public static string XDays {
            get {
                return ResourceManager.GetString("XDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} horas.
        /// </summary>
        public static string XHours {
            get {
                return ResourceManager.GetString("XHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minutos.
        /// </summary>
        public static string XMinutes {
            get {
                return ResourceManager.GetString("XMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} segundos.
        /// </summary>
        public static string XSeconds {
            get {
                return ResourceManager.GetString("XSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YB.
        /// </summary>
        public static string YB {
            get {
                return ResourceManager.GetString("YB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yottabytes.
        /// </summary>
        public static string YBl {
            get {
                return ResourceManager.GetString("YBl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YiB.
        /// </summary>
        public static string YiB {
            get {
                return ResourceManager.GetString("YiB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yobibytes.
        /// </summary>
        public static string YiBl {
            get {
                return ResourceManager.GetString("YiBl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZB.
        /// </summary>
        public static string ZB {
            get {
                return ResourceManager.GetString("ZB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zettabytes.
        /// </summary>
        public static string ZBl {
            get {
                return ResourceManager.GetString("ZBl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZiB.
        /// </summary>
        public static string ZiB {
            get {
                return ResourceManager.GetString("ZiB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zebibytes.
        /// </summary>
        public static string ZiBl {
            get {
                return ResourceManager.GetString("ZiBl", resourceCulture);
            }
        }
    }
}
