//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheXDS.MCART.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheXDS.MCART.Resources.Strings.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La escritura de un valor de tipo {0} no está soportada por este método. Utilice el método {1} definido en la clase {2}..
        /// </summary>
        public static string BinWriteXNotSupported {
            get {
                return ResourceManager.GetString("BinWriteXNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede escribir el objeto de tipo {0}..
        /// </summary>
        public static string CantWriteObjOfT {
            get {
                return ResourceManager.GetString("CantWriteObjOfT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operación circular detectada..
        /// </summary>
        public static string CircularOpDetected {
            get {
                return ResourceManager.GetString("CircularOpDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La clase especificada no es instanciable..
        /// </summary>
        public static string ClassNotInstantiable {
            get {
                return ResourceManager.GetString("ClassNotInstantiable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La clase &apos;{0}&apos; no pudo ser instanciada con los parámetros de constructor especificados..
        /// </summary>
        public static string ClassNotInstantiableWIthArgs {
            get {
                return ResourceManager.GetString("ClassNotInstantiableWIthArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La clase {0} no es instanciable..
        /// </summary>
        public static string ClassXNotinstantiable {
            get {
                return ResourceManager.GetString("ClassXNotinstantiable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existen datos con el id &apos;{0}&apos;..
        /// </summary>
        public static string DuplicateData {
            get {
                return ResourceManager.GetString("DuplicateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La colección no contiene elementos..
        /// </summary>
        public static string EmptyCollection {
            get {
                return ResourceManager.GetString("EmptyCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se esperaba un tipo de colección enumerable..
        /// </summary>
        public static string EnumerableTypeExpected {
            get {
                return ResourceManager.GetString("EnumerableTypeExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tipo {0} no es un tipo de enumeración válido..
        /// </summary>
        public static string EnumTypeExpected {
            get {
                return ResourceManager.GetString("EnumTypeExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha producido un error al intentar cargar el contenido de la licencia..
        /// </summary>
        public static string ErrorLoadingLicense {
            get {
                return ResourceManager.GetString("ErrorLoadingLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error al cargar el recurso {0}..
        /// </summary>
        public static string ErrorLoadingRes {
            get {
                return ResourceManager.GetString("ErrorLoadingRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El valor del campo {0} no debe ser null..
        /// </summary>
        public static string FieldValueShouldNotBeNull {
            get {
                return ResourceManager.GetString("FieldValueShouldNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El formato {0} no está soportado..
        /// </summary>
        public static string FormatNotSupported {
            get {
                return ResourceManager.GetString("FormatNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se esperaba un tipo de interfaz..
        /// </summary>
        public static string InterfaceExpected {
            get {
                return ResourceManager.GetString("InterfaceExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tipo no implementa la interfaz &apos;{0}&apos;..
        /// </summary>
        public static string InterfaceNotImplented {
            get {
                return ResourceManager.GetString("InterfaceNotImplented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El argumento {0} contiene un valor inválido en este contexto..
        /// </summary>
        public static string InvalidArgument {
            get {
                return ResourceManager.GetString("InvalidArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El método {0} ha devuelto un valor inválido en este contexto..
        /// </summary>
        public static string InvalidFuncReturnValue {
            get {
                return ResourceManager.GetString("InvalidFuncReturnValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El método {0} ha devuelto {1}, el cual no es un valor válido en este contexto..
        /// </summary>
        public static string InvalidFuncXReturnValue {
            get {
                return ResourceManager.GetString("InvalidFuncXReturnValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El método no tiene una firma válida..
        /// </summary>
        public static string InvalidMethodSignature {
            get {
                return ResourceManager.GetString("InvalidMethodSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El método &apos;{0}&apos; no tiene una firma válida..
        /// </summary>
        public static string InvalidMethodXSignature {
            get {
                return ResourceManager.GetString("InvalidMethodXSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El método ha devuelto un valor inválido en este contexto..
        /// </summary>
        public static string InvalidReturnValue {
            get {
                return ResourceManager.GetString("InvalidReturnValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La expresión utilizada en este contexto debe seleccionar a un miembro..
        /// </summary>
        public static string InvalidSelectorExpression {
            get {
                return ResourceManager.GetString("InvalidSelectorExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tipo no es válido en este contexto..
        /// </summary>
        public static string InvalidType {
            get {
                return ResourceManager.GetString("InvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El URI apunta a un recurso no válido..
        /// </summary>
        public static string InvalidUri {
            get {
                return ResourceManager.GetString("InvalidUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El valor proporcionado no es válido en este contexto..
        /// </summary>
        public static string InvalidValue {
            get {
                return ResourceManager.GetString("InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tipo {0} no es válido en este contexto..
        /// </summary>
        public static string InvalidXType {
            get {
                return ResourceManager.GetString("InvalidXType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El URI que apunta al recurso &apos;{0}&apos; no es válido..
        /// </summary>
        public static string InvalidXUri {
            get {
                return ResourceManager.GetString("InvalidXUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El valor {0} no es válido en este contexto..
        /// </summary>
        public static string InvalidXValue {
            get {
                return ResourceManager.GetString("InvalidXValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  en {0}.
        /// </summary>
        public static string InX {
            get {
                return ResourceManager.GetString("InX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La colección debe contener a ambos objetos..
        /// </summary>
        public static string ListMustContainBoth {
            get {
                return ResourceManager.GetString("ListMustContainBoth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensamblados en el dominio de aplicación (en orden de carga):.
        /// </summary>
        public static string LoadedAssemblies {
            get {
                return ResourceManager.GetString("LoadedAssemblies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El argumento mínimo debe ser inferior o igual al máximo..
        /// </summary>
        public static string MinGtMax {
            get {
                return ResourceManager.GetString("MinGtMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La declaración del tipo {0} requiere un atributo de Guid para utilizarse en este contexto..
        /// </summary>
        public static string MissingGuidAttrFromType {
            get {
                return ResourceManager.GetString("MissingGuidAttrFromType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fin de la lista de excepciones internas..
        /// </summary>
        public static string NoInner {
            get {
                return ResourceManager.GetString("NoInner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay información de pila disponible..
        /// </summary>
        public static string NoStackInfo {
            get {
                return ResourceManager.GetString("NoStackInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El objeto está deshabilitado..
        /// </summary>
        public static string ObjectIsDisabled {
            get {
                return ResourceManager.GetString("ObjectIsDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La propiedad &apos;{0}&apos; es de sólo lectura..
        /// </summary>
        public static string PropIsReadOnly {
            get {
                return ResourceManager.GetString("PropIsReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo o propiedad &apos;{0}&apos; del parámetro &apos;{1}&apos; no debe ser null..
        /// </summary>
        public static string PropXOnArgYNull {
            get {
                return ResourceManager.GetString("PropXOnArgYNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tipo de destino ({0}) no coincide con el tipo de origen ({1})..
        /// </summary>
        public static string ShallowCopyTo_Contract_DestinationTypeMismatch {
            get {
                return ResourceManager.GetString("ShallowCopyTo_Contract_DestinationTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tipo de origen ({0}) no coincide con el tipo de destino ({1})..
        /// </summary>
        public static string ShallowCopyTo_Contract_OriginTypeMismatch {
            get {
                return ResourceManager.GetString("ShallowCopyTo_Contract_OriginTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La pila está vacía..
        /// </summary>
        public static string StackUnderflow {
            get {
                return ResourceManager.GetString("StackUnderflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha detectado una manipulación inesperada de la aplicación, o la memoria del proceso ha sido corrompida. Detenga la ejecución del programa inmediatamente..
        /// </summary>
        public static string TamperDetected {
            get {
                return ResourceManager.GetString("TamperDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El valor {0} está fuera del rango de valores definidos para la enumeración {1}..
        /// </summary>
        public static string UndefinedEnum {
            get {
                return ResourceManager.GetString("UndefinedEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tipo {0} no es válido en este contexto. Se esperaba un tipo {1}..
        /// </summary>
        public static string UnexpectedType {
            get {
                return ResourceManager.GetString("UnexpectedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El valor debe estar entre {0} y {1}..
        /// </summary>
        public static string ValueMustBeBetweenXandY {
            get {
                return ResourceManager.GetString("ValueMustBeBetweenXandY", resourceCulture);
            }
        }
    }
}
