//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheXDS.MCART.Wpf.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheXDS.MCART.Resources.Strings.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acerca de MCART....
        /// </summary>
        public static string AboutMCART {
            get {
                return ResourceManager.GetString("AboutMCART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abstracto.
        /// </summary>
        public static string Abstract {
            get {
                return ResourceManager.GetString("Abstract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipos base.
        /// </summary>
        public static string BaseTypes {
            get {
                return ResourceManager.GetString("BaseTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string BtnCancel {
            get {
                return ResourceManager.GetString("BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrar.
        /// </summary>
        public static string BtnDel {
            get {
                return ResourceManager.GetString("BtnDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string BtnEdit {
            get {
                return ResourceManager.GetString("BtnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo.
        /// </summary>
        public static string BtnNew {
            get {
                return ResourceManager.GetString("BtnNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        public static string BtnSave {
            get {
                return ResourceManager.GetString("BtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensamblado de declaración.
        /// </summary>
        public static string DeclaringAssembly {
            get {
                return ResourceManager.GetString("DeclaringAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor predeterminado.
        /// </summary>
        public static string DefaultValue {
            get {
                return ResourceManager.GetString("DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo dinámico.
        /// </summary>
        public static string DynamicType {
            get {
                return ResourceManager.GetString("DynamicType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argumentos de tipo genérico.
        /// </summary>
        public static string GenericArgs {
            get {
                return ResourceManager.GetString("GenericArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo genérico.
        /// </summary>
        public static string GenericType {
            get {
                return ResourceManager.GetString("GenericType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instanciable.
        /// </summary>
        public static string Instantiable {
            get {
                return ResourceManager.GetString("Instantiable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interfaces.
        /// </summary>
        public static string Interfaces {
            get {
                return ResourceManager.GetString("Interfaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de referencia (Clase).
        /// </summary>
        public static string IsClass {
            get {
                return ResourceManager.GetString("IsClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de enumeración.
        /// </summary>
        public static string IsEnum {
            get {
                return ResourceManager.GetString("IsEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo genérico construido.
        /// </summary>
        public static string IsGenericBuilt {
            get {
                return ResourceManager.GetString("IsGenericBuilt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interfaz.
        /// </summary>
        public static string IsInterface {
            get {
                return ResourceManager.GetString("IsInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo primitivo.
        /// </summary>
        public static string IsPrimitive {
            get {
                return ResourceManager.GetString("IsPrimitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo sellado.
        /// </summary>
        public static string IsSealed {
            get {
                return ResourceManager.GetString("IsSealed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo estático.
        /// </summary>
        public static string IsStatic {
            get {
                return ResourceManager.GetString("IsStatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de valor.
        /// </summary>
        public static string IsValueType {
            get {
                return ResourceManager.GetString("IsValueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espacio de nombres.
        /// </summary>
        public static string Namespace {
            get {
                return ResourceManager.GetString("Namespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva instancia.
        /// </summary>
        public static string NewInstance {
            get {
                return ResourceManager.GetString("NewInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo registro.
        /// </summary>
        public static string NewReg {
            get {
                return ResourceManager.GetString("NewReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  de .
        /// </summary>
        public static string Of {
            get {
                return ResourceManager.GetString("Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propiedades.
        /// </summary>
        public static string Properties {
            get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miembros públicos.
        /// </summary>
        public static string PublicMembers {
            get {
                return ResourceManager.GetString("PublicMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar....
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver licencias de terceros....
        /// </summary>
        public static string See3rdPartyLicenses {
            get {
                return ResourceManager.GetString("See3rdPartyLicenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver licencia....
        /// </summary>
        public static string SeeLicense {
            get {
                return ResourceManager.GetString("SeeLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo serializable.
        /// </summary>
        public static string Serializable {
            get {
                return ResourceManager.GetString("Serializable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre del tipo.
        /// </summary>
        public static string TypeName {
            get {
                return ResourceManager.GetString("TypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versión.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} de {1}.
        /// </summary>
        public static string XOfY {
            get {
                return ResourceManager.GetString("XOfY", resourceCulture);
            }
        }
    }
}
