//
//  MainWindow.cs
//
//  This file has been generated by the Stetic GUI designer.
//
//  This program is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with this program.  If not, see <http://www.gnu.org/licenses/>.

public partial class MainWindow
{
    private Gtk.UIManager UIManager;
    private Gtk.Action ArchivoAction;
    private Gtk.Action PruebasAction;
    private Gtk.Action CapturaDePantallaAction;
    private new Gtk.Action Action;
    private Gtk.Action SalirAction;
    private Gtk.Action ContraseasAction;
    private Gtk.Action ProbarContraseaAction;
    private Gtk.Action EstablecerContraseaAction;
    private Gtk.Action GenerarContraseaAction;
    private Gtk.Action PinAction;
    private Gtk.Action ContraseaSencillaAction;
    private Gtk.Action ContraseaComplejaAction;
    private Gtk.Action PluginsAction;
    private Gtk.Action AyudaAction;
    private Gtk.Action InfoDePluginsAction1;
    private Gtk.Action AcercaDeMCARTAction;
    private Gtk.VBox vbox1;
    private Gtk.MenuBar mnuMain;
    private Gtk.Image image1;
    /// <summary>
    /// Construye esta ventana.
    /// </summary>
    protected virtual void Build()
    {
        Stetic.Gui.Initialize(this);
        UIManager = new Gtk.UIManager();
        Gtk.ActionGroup w1 = new Gtk.ActionGroup("Default");
        ArchivoAction = new Gtk.Action("ArchivoAction", Mono.Unix.Catalog.GetString("Archivo"), null, null)
        {
            ShortLabel = Mono.Unix.Catalog.GetString("Archivo")
        };
        w1.Add(ArchivoAction, null);
        PruebasAction = new Gtk.Action("PruebasAction", Mono.Unix.Catalog.GetString("Pruebas"), null, null)
        {
            ShortLabel = Mono.Unix.Catalog.GetString("Pruebas")
        };
        w1.Add(PruebasAction, null);
        CapturaDePantallaAction = new Gtk.Action("CapturaDePantallaAction", Mono.Unix.Catalog.GetString("Captura de pantalla"), null, null)
        {
            ShortLabel = Mono.Unix.Catalog.GetString("Captura de pantalla")
        };
        w1.Add(CapturaDePantallaAction, null);
        Action = new Gtk.Action("Action", Mono.Unix.Catalog.GetString("-"), null, null)
        {
            ShortLabel = Mono.Unix.Catalog.GetString("-")
        };
        w1.Add(Action, null);
        SalirAction = new Gtk.Action("SalirAction", Mono.Unix.Catalog.GetString("Salir"), null, null)
        {
            ShortLabel = Mono.Unix.Catalog.GetString("Salir")
        };
        w1.Add(SalirAction, null);
        ContraseasAction = new Gtk.Action("ContraseasAction", Mono.Unix.Catalog.GetString("Contraseñas"), null, null)
        {
            ShortLabel = Mono.Unix.Catalog.GetString("Contraseñas")
        };
        w1.Add(ContraseasAction, null);
        ProbarContraseaAction = new Gtk.Action("ProbarContraseaAction", Mono.Unix.Catalog.GetString("Probar contraseña..."), null, null)
        {
            ShortLabel = Mono.Unix.Catalog.GetString("Probar contraseña...")
        };
        w1.Add(ProbarContraseaAction, null);
        EstablecerContraseaAction = new Gtk.Action("EstablecerContraseaAction", Mono.Unix.Catalog.GetString("Establecer contraseña..."), null, null)
        {
            ShortLabel = Mono.Unix.Catalog.GetString("Establecer contraseña...")
        };
        w1.Add(EstablecerContraseaAction, null);
        GenerarContraseaAction = new Gtk.Action("GenerarContraseaAction", Mono.Unix.Catalog.GetString("Generar contraseña"), null, null)
        {
            ShortLabel = Mono.Unix.Catalog.GetString("Generar contraseña")
        };
        w1.Add(GenerarContraseaAction, null);
        PinAction = new Gtk.Action("PinAction", Mono.Unix.Catalog.GetString("Pin..."), null, null)
        {
            ShortLabel = Mono.Unix.Catalog.GetString("Pin...")
        };
        w1.Add(PinAction, null);
        ContraseaSencillaAction = new Gtk.Action("ContraseaSencillaAction", Mono.Unix.Catalog.GetString("Contraseña sencilla"), null, null)
        {
            ShortLabel = Mono.Unix.Catalog.GetString("Contraseña sencilla")
        };
        w1.Add(ContraseaSencillaAction, null);
        ContraseaComplejaAction = new Gtk.Action("ContraseaComplejaAction", Mono.Unix.Catalog.GetString("Contraseña compleja"), null, null)
        {
            ShortLabel = Mono.Unix.Catalog.GetString("Contraseña compleja")
        };
        w1.Add(ContraseaComplejaAction, null);
        PluginsAction = new Gtk.Action("PluginsAction", Mono.Unix.Catalog.GetString("Plugins"), null, null)
        {
            ShortLabel = Mono.Unix.Catalog.GetString("Plugins")
        };
        w1.Add(PluginsAction, null);
        AyudaAction = new Gtk.Action("AyudaAction", Mono.Unix.Catalog.GetString("Ayuda"), null, null)
        {
            ShortLabel = Mono.Unix.Catalog.GetString("Ayuda")
        };
        w1.Add(AyudaAction, null);
        InfoDePluginsAction1 = new Gtk.Action("InfoDePluginsAction1", Mono.Unix.Catalog.GetString("Info de plugins..."), null, null)
        {
            ShortLabel = Mono.Unix.Catalog.GetString("Info de plugins...")
        };
        w1.Add(InfoDePluginsAction1, null);
        AcercaDeMCARTAction = new Gtk.Action("AcercaDeMCARTAction", Mono.Unix.Catalog.GetString("Acerca de MCART..."), null, null)
        {
            ShortLabel = Mono.Unix.Catalog.GetString("Acerca de MCART...")
        };
        w1.Add(AcercaDeMCARTAction, null);
        UIManager.InsertActionGroup(w1, 0);
        AddAccelGroup(UIManager.AccelGroup);
        Name = "MainWindow";
        Title = Mono.Unix.Catalog.GetString("MainWindow");
        WindowPosition = ((Gtk.WindowPosition)(4));
        vbox1 = new Gtk.VBox { Name = "vbox1", Spacing = 6 };
        UIManager.AddUiFromString(@"<ui><menubar name='mnuMain'><menu name='ArchivoAction' action='ArchivoAction'><menuitem name='CapturaDePantallaAction' action='CapturaDePantallaAction'/><separator/><menuitem name='SalirAction' action='SalirAction'/></menu><menu name='PruebasAction' action='PruebasAction'><menu name='ContraseasAction' action='ContraseasAction'><menuitem name='ProbarContraseaAction' action='ProbarContraseaAction'/><menuitem name='EstablecerContraseaAction' action='EstablecerContraseaAction'/><menu name='GenerarContraseaAction' action='GenerarContraseaAction'><menuitem name='PinAction' action='PinAction'/><menuitem name='ContraseaSencillaAction' action='ContraseaSencillaAction'/><menuitem name='ContraseaComplejaAction' action='ContraseaComplejaAction'/></menu></menu></menu><menu name='PluginsAction' action='PluginsAction'/><menu name='AyudaAction' action='AyudaAction'><menuitem name='InfoDePluginsAction1' action='InfoDePluginsAction1'/><menuitem name='AcercaDeMCARTAction' action='AcercaDeMCARTAction'/></menu></menubar></ui>");
        mnuMain = ((Gtk.MenuBar)(UIManager.GetWidget("/mnuMain")));
        mnuMain.Name = "mnuMain";
        vbox1.Add(mnuMain);
        Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(vbox1[mnuMain]));
        w2.Position = 0;
        w2.Expand = false;
        w2.Fill = false;
        image1 = new Gtk.Image { Name = "image1" };
        vbox1.Add(image1);
        Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(vbox1[image1]));
        w3.Position = 1;
        w3.Expand = false;
        w3.Fill = false;
        Add(vbox1);
        Child?.ShowAll();
        DefaultWidth = 466;
        DefaultHeight = 300;
        Show();
        DeleteEvent += new Gtk.DeleteEventHandler(OnDeleteEvent);
        SalirAction.Activated += new System.EventHandler(OnSalirActionActivated);
        InfoDePluginsAction1.Activated += new System.EventHandler(OnInfoDePluginsAction1Activated);
    }
}