//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheXDS.MCART.PluginSupport.Legacy.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheXDS.MCART.PluginSupport.Legacy.Resources.Strings.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No fue posible cargar la información del plugin {0}..
        /// </summary>
        internal static string CantShowPluginInfo {
            get {
                return ResourceManager.GetString("CantShowPluginInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EL uso de la clase especificada es peligroso..
        /// </summary>
        internal static string ClassIsDangerous {
            get {
                return ResourceManager.GetString("ClassIsDangerous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La clase especificada no es un plugin..
        /// </summary>
        internal static string ClassIsNotPlugin {
            get {
                return ResourceManager.GetString("ClassIsNotPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El uso de la clase &apos;{0}&apos; es peligroso..
        /// </summary>
        internal static string ClassXIsDangerous {
            get {
                return ResourceManager.GetString("ClassXIsDangerous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La clase {0} no es un plugin..
        /// </summary>
        internal static string ClassXIsNotPlugin {
            get {
                return ResourceManager.GetString("ClassXIsNotPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La característica no está disponible..
        /// </summary>
        internal static string FeatureNotAvailable {
            get {
                return ResourceManager.GetString("FeatureNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El ensamblado especificado no es válido..
        /// </summary>
        internal static string InvalidAssembly {
            get {
                return ResourceManager.GetString("InvalidAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El archivo &quot;{0}&quot; no contiene un ensamblado válido..
        /// </summary>
        internal static string InvalidXAssembly {
            get {
                return ResourceManager.GetString("InvalidXAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La llamada al método especificado es peligrosa..
        /// </summary>
        internal static string MethodIsDangerous {
            get {
                return ResourceManager.GetString("MethodIsDangerous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La llamada al método &apos;{0}&apos; es peligrosa..
        /// </summary>
        internal static string MethodXIsDangerous {
            get {
                return ResourceManager.GetString("MethodXIsDangerous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El plugin no se inicializó..
        /// </summary>
        internal static string PluginDidntInit {
            get {
                return ResourceManager.GetString("PluginDidntInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Plugin ha encontrado un error..
        /// </summary>
        internal static string PluginException {
            get {
                return ResourceManager.GetString("PluginException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El plugin {0} ha encontrado un error..
        /// </summary>
        internal static string PluginXException {
            get {
                return ResourceManager.GetString("PluginXException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El objeto no puede ser utilizado..
        /// </summary>
        internal static string UnusableObject {
            get {
                return ResourceManager.GetString("UnusableObject", resourceCulture);
            }
        }
    }
}
