
// This file has been generated by the GUI designer. Do not modify.
namespace MCART.Forms
{
	public partial class PluginBrowser
	{
		private global::Gtk.HPaned hpaned1;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView TrvPlugins;

		private global::Gtk.Table table3;

		private global::Gtk.HBox hbox2;

		private global::Gtk.Entry TxtVer;

		private global::Gtk.CheckButton ChkIsBeta;

		private global::Gtk.CheckButton ChkIsUnafe;

		private global::Gtk.Label label6;

		private global::Gtk.Label label7;

		private global::Gtk.Label label9;

		private global::Gtk.Table table5;

		private global::Gtk.Button BtnTest;

		private global::Gtk.CheckButton checkbutton10;

		private global::Gtk.CheckButton checkbutton8;

		private global::Gtk.Entry TxtMinVer;

		private global::Gtk.CheckButton checkbutton9;

		private global::Gtk.Entry TxtTargetVer;

		private global::Gtk.Label label13;

		private global::Gtk.Label label14;

		private global::Gtk.Entry TxtCopyright;

		private global::Gtk.Entry TxtName;

		private global::Gtk.VBox vbox4;

		private global::Gtk.Label label8;

		private global::Gtk.Entry TxtDesc;

		private global::Gtk.VBox vbox6;

		private global::Gtk.Label label10;

		private global::Gtk.ScrolledWindow GtkScrolledWindow2;

		private global::Gtk.TreeView TrvInterfaces;

		private global::Gtk.Button buttonOk;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget MCART.Forms.PluginBrowser
			this.Name = "MCART.Forms.PluginBrowser";
			this.Title = global::Mono.Unix.Catalog.GetString("dialog1");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child MCART.Forms.PluginBrowser.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.hpaned1 = new global::Gtk.HPaned();
			this.hpaned1.CanFocus = true;
			this.hpaned1.Name = "hpaned1";
			this.hpaned1.Position = 246;
			// Container child hpaned1.Gtk.Paned+PanedChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.TrvPlugins = new global::Gtk.TreeView();
			this.TrvPlugins.CanFocus = true;
			this.TrvPlugins.Name = "TrvPlugins";
			this.GtkScrolledWindow.Add(this.TrvPlugins);
			this.hpaned1.Add(this.GtkScrolledWindow);
			global::Gtk.Paned.PanedChild w3 = ((global::Gtk.Paned.PanedChild)(this.hpaned1[this.GtkScrolledWindow]));
			w3.Resize = false;
			// Container child hpaned1.Gtk.Paned+PanedChild
			this.table3 = new global::Gtk.Table(((uint)(6)), ((uint)(2)), false);
			this.table3.Name = "table3";
			this.table3.RowSpacing = ((uint)(6));
			this.table3.ColumnSpacing = ((uint)(6));
			// Container child table3.Gtk.Table+TableChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.TxtVer = new global::Gtk.Entry();
			this.TxtVer.CanFocus = true;
			this.TxtVer.Name = "TxtVer";
			this.TxtVer.IsEditable = false;
			this.TxtVer.InvisibleChar = '●';
			this.hbox2.Add(this.TxtVer);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.TxtVer]));
			w4.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.ChkIsBeta = new global::Gtk.CheckButton();
			this.ChkIsBeta.Sensitive = false;
			this.ChkIsBeta.CanFocus = true;
			this.ChkIsBeta.Name = "ChkIsBeta";
			this.ChkIsBeta.Label = global::Mono.Unix.Catalog.GetString("Beta");
			this.ChkIsBeta.DrawIndicator = true;
			this.ChkIsBeta.UseUnderline = true;
			this.hbox2.Add(this.ChkIsBeta);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.ChkIsBeta]));
			w5.Position = 1;
			w5.Expand = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.ChkIsUnafe = new global::Gtk.CheckButton();
			this.ChkIsUnafe.Sensitive = false;
			this.ChkIsUnafe.CanFocus = true;
			this.ChkIsUnafe.Name = "ChkIsUnafe";
			this.ChkIsUnafe.Label = global::Mono.Unix.Catalog.GetString("Inestable");
			this.ChkIsUnafe.DrawIndicator = true;
			this.ChkIsUnafe.UseUnderline = true;
			this.hbox2.Add(this.ChkIsUnafe);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.ChkIsUnafe]));
			w6.Position = 2;
			w6.Expand = false;
			this.table3.Add(this.hbox2);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table3[this.hbox2]));
			w7.TopAttach = ((uint)(1));
			w7.BottomAttach = ((uint)(2));
			w7.LeftAttach = ((uint)(1));
			w7.RightAttach = ((uint)(2));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label6 = new global::Gtk.Label();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("Nombre");
			this.table3.Add(this.label6);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table3[this.label6]));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label7 = new global::Gtk.Label();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("Versión");
			this.table3.Add(this.label7);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table3[this.label7]));
			w9.TopAttach = ((uint)(1));
			w9.BottomAttach = ((uint)(2));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label9 = new global::Gtk.Label();
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString("Copyright");
			this.table3.Add(this.label9);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table3[this.label9]));
			w10.TopAttach = ((uint)(3));
			w10.BottomAttach = ((uint)(4));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.table5 = new global::Gtk.Table(((uint)(3)), ((uint)(2)), false);
			this.table5.Name = "table5";
			this.table5.RowSpacing = ((uint)(6));
			this.table5.ColumnSpacing = ((uint)(6));
			// Container child table5.Gtk.Table+TableChild
			this.BtnTest = new global::Gtk.Button();
			this.BtnTest.Sensitive = false;
			this.BtnTest.CanFocus = true;
			this.BtnTest.Name = "BtnTest";
			this.BtnTest.UseUnderline = true;
			this.BtnTest.Label = global::Mono.Unix.Catalog.GetString("Probar interacciones...");
			this.table5.Add(this.BtnTest);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table5[this.BtnTest]));
			w11.TopAttach = ((uint)(2));
			w11.BottomAttach = ((uint)(3));
			w11.LeftAttach = ((uint)(1));
			w11.RightAttach = ((uint)(2));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.checkbutton10 = new global::Gtk.CheckButton();
			this.checkbutton10.Sensitive = false;
			this.checkbutton10.CanFocus = true;
			this.checkbutton10.Name = "checkbutton10";
			this.checkbutton10.Label = global::Mono.Unix.Catalog.GetString("Contiene interacciones");
			this.checkbutton10.DrawIndicator = true;
			this.checkbutton10.UseUnderline = true;
			this.table5.Add(this.checkbutton10);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table5[this.checkbutton10]));
			w12.TopAttach = ((uint)(2));
			w12.BottomAttach = ((uint)(3));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.checkbutton8 = new global::Gtk.CheckButton();
			this.checkbutton8.Sensitive = false;
			this.checkbutton8.CanFocus = true;
			this.checkbutton8.Name = "checkbutton8";
			this.checkbutton8.Label = global::Mono.Unix.Catalog.GetString("checkbutton8");
			this.checkbutton8.DrawIndicator = true;
			this.checkbutton8.UseUnderline = true;
			this.checkbutton8.Remove(this.checkbutton8.Child);
			// Container child checkbutton8.Gtk.Container+ContainerChild
			this.TxtMinVer = new global::Gtk.Entry();
			this.TxtMinVer.CanFocus = true;
			this.TxtMinVer.Name = "TxtMinVer";
			this.TxtMinVer.IsEditable = false;
			this.TxtMinVer.InvisibleChar = '●';
			this.checkbutton8.Add(this.TxtMinVer);
			this.table5.Add(this.checkbutton8);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table5[this.checkbutton8]));
			w14.TopAttach = ((uint)(1));
			w14.BottomAttach = ((uint)(2));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.checkbutton9 = new global::Gtk.CheckButton();
			this.checkbutton9.Sensitive = false;
			this.checkbutton9.CanFocus = true;
			this.checkbutton9.Name = "checkbutton9";
			this.checkbutton9.Label = global::Mono.Unix.Catalog.GetString("checkbutton9");
			this.checkbutton9.DrawIndicator = true;
			this.checkbutton9.UseUnderline = true;
			this.checkbutton9.Remove(this.checkbutton9.Child);
			// Container child checkbutton9.Gtk.Container+ContainerChild
			this.TxtTargetVer = new global::Gtk.Entry();
			this.TxtTargetVer.CanFocus = true;
			this.TxtTargetVer.Name = "TxtTargetVer";
			this.TxtTargetVer.IsEditable = false;
			this.TxtTargetVer.InvisibleChar = '●';
			this.checkbutton9.Add(this.TxtTargetVer);
			this.table5.Add(this.checkbutton9);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table5[this.checkbutton9]));
			w16.TopAttach = ((uint)(1));
			w16.BottomAttach = ((uint)(2));
			w16.LeftAttach = ((uint)(1));
			w16.RightAttach = ((uint)(2));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.label13 = new global::Gtk.Label();
			this.label13.Name = "label13";
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString("MCART mínima");
			this.table5.Add(this.label13);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table5[this.label13]));
			w17.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.label14 = new global::Gtk.Label();
			this.label14.Name = "label14";
			this.label14.LabelProp = global::Mono.Unix.Catalog.GetString("MCART objetivo");
			this.table5.Add(this.label14);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table5[this.label14]));
			w18.LeftAttach = ((uint)(1));
			w18.RightAttach = ((uint)(2));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			this.table3.Add(this.table5);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table3[this.table5]));
			w19.TopAttach = ((uint)(5));
			w19.BottomAttach = ((uint)(6));
			w19.RightAttach = ((uint)(2));
			w19.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.TxtCopyright = new global::Gtk.Entry();
			this.TxtCopyright.CanFocus = true;
			this.TxtCopyright.Name = "TxtCopyright";
			this.TxtCopyright.IsEditable = false;
			this.TxtCopyright.InvisibleChar = '●';
			this.table3.Add(this.TxtCopyright);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table3[this.TxtCopyright]));
			w20.TopAttach = ((uint)(3));
			w20.BottomAttach = ((uint)(4));
			w20.LeftAttach = ((uint)(1));
			w20.RightAttach = ((uint)(2));
			w20.XOptions = ((global::Gtk.AttachOptions)(4));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.TxtName = new global::Gtk.Entry();
			this.TxtName.CanFocus = true;
			this.TxtName.Name = "TxtName";
			this.TxtName.IsEditable = false;
			this.TxtName.InvisibleChar = '●';
			this.table3.Add(this.TxtName);
			global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table3[this.TxtName]));
			w21.LeftAttach = ((uint)(1));
			w21.RightAttach = ((uint)(2));
			w21.XOptions = ((global::Gtk.AttachOptions)(4));
			w21.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.vbox4 = new global::Gtk.VBox();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.label8 = new global::Gtk.Label();
			this.label8.Name = "label8";
			this.label8.Xalign = 0F;
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString("Descripción");
			this.vbox4.Add(this.label8);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.label8]));
			w22.Position = 0;
			w22.Expand = false;
			w22.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.TxtDesc = new global::Gtk.Entry();
			this.TxtDesc.CanFocus = true;
			this.TxtDesc.Name = "TxtDesc";
			this.TxtDesc.IsEditable = true;
			this.TxtDesc.InvisibleChar = '●';
			this.vbox4.Add(this.TxtDesc);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.TxtDesc]));
			w23.Position = 1;
			w23.Expand = false;
			w23.Fill = false;
			this.table3.Add(this.vbox4);
			global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.table3[this.vbox4]));
			w24.TopAttach = ((uint)(2));
			w24.BottomAttach = ((uint)(3));
			w24.RightAttach = ((uint)(2));
			w24.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.vbox6 = new global::Gtk.VBox();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.label10 = new global::Gtk.Label();
			this.label10.Name = "label10";
			this.label10.Xalign = 0F;
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString("Interfaces implementadas");
			this.vbox6.Add(this.label10);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.label10]));
			w25.Position = 0;
			w25.Expand = false;
			w25.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
			this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
			this.TrvInterfaces = new global::Gtk.TreeView();
			this.TrvInterfaces.CanFocus = true;
			this.TrvInterfaces.Name = "TrvInterfaces";
			this.TrvInterfaces.HeadersVisible = false;
			this.GtkScrolledWindow2.Add(this.TrvInterfaces);
			this.vbox6.Add(this.GtkScrolledWindow2);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.GtkScrolledWindow2]));
			w27.Position = 1;
			this.table3.Add(this.vbox6);
			global::Gtk.Table.TableChild w28 = ((global::Gtk.Table.TableChild)(this.table3[this.vbox6]));
			w28.TopAttach = ((uint)(4));
			w28.BottomAttach = ((uint)(5));
			w28.RightAttach = ((uint)(2));
			this.hpaned1.Add(this.table3);
			w1.Add(this.hpaned1);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(w1[this.hpaned1]));
			w30.Position = 0;
			// Internal child MCART.Forms.PluginBrowser.ActionArea
			global::Gtk.HButtonBox w31 = this.ActionArea;
			w31.Name = "dialog1_ActionArea";
			w31.Spacing = 10;
			w31.BorderWidth = ((uint)(5));
			w31.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-close";
			this.AddActionWidget(this.buttonOk, -7);
			global::Gtk.ButtonBox.ButtonBoxChild w32 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w31[this.buttonOk]));
			w32.Expand = false;
			w32.Fill = false;
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 632;
			this.DefaultHeight = 418;
			this.Show();
			this.BtnTest.Clicked += new global::System.EventHandler(this.OnBtnTestClicked);
			this.buttonOk.Clicked += new global::System.EventHandler(this.BtnClose_Click);
		}
	}
}
