//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheXDS.MCART.Security.Legacy.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheXDS.MCART.Security.Legacy.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Evite el uso de contraseñas comunes..
        /// </summary>
        internal static string AvoidCommonPasswords {
            get {
                return ResourceManager.GetString("AvoidCommonPasswords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Evite utilizar el año actual en la contraseña..
        /// </summary>
        internal static string AvoidYears {
            get {
                return ResourceManager.GetString("AvoidYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Evaluador de reglas comunes..
        /// </summary>
        internal static string CommonEvaluator {
            get {
                return ResourceManager.GetString("CommonEvaluator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se evalúa la contraseña contra reglas comunmente utilizadas, como ser longitud, uso de mayúsculas y minúsculas, letras y símbolos..
        /// </summary>
        internal static string CommonEvaluatorDesc {
            get {
                return ResourceManager.GetString("CommonEvaluatorDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Evaluador complejo de contraseñas.
        /// </summary>
        internal static string ComplexEvaluator {
            get {
                return ResourceManager.GetString("ComplexEvaluator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña compleja.
        /// </summary>
        internal static string ComplexPw {
            get {
                return ResourceManager.GetString("ComplexPw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar contraseña.
        /// </summary>
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña criptográfica.
        /// </summary>
        internal static string CryptoPw {
            get {
                return ResourceManager.GetString("CryptoPw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introduzca una contraseña para continuar..
        /// </summary>
        internal static string EmptyPassword {
            get {
                return ResourceManager.GetString("EmptyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Evaluador extendido de contraseñas.
        /// </summary>
        internal static string ExtendedEvaluator {
            get {
                return ResourceManager.GetString("ExtendedEvaluator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} Incluye {1}..
        /// </summary>
        internal static string IncludesX {
            get {
                return ResourceManager.GetString("IncludesX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} Incluya {1}..
        /// </summary>
        internal static string IncludeX {
            get {
                return ResourceManager.GetString("IncludeX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regla nula.
        /// </summary>
        internal static string NullPwEvalRule {
            get {
                return ResourceManager.GetString("NullPwEvalRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esta regla no evaluará la contraseña, sino que devolverá un valor constante que ayuda a balancear el puntaje de otras reglas en el total..
        /// </summary>
        internal static string NullPwEvalRule2 {
            get {
                return ResourceManager.GetString("NullPwEvalRule2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Indicio de contraseña.
        /// </summary>
        internal static string PasswordHint {
            get {
                return ResourceManager.GetString("PasswordHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número PIN.
        /// </summary>
        internal static string PinNumber {
            get {
                return ResourceManager.GetString("PinNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generador de contraseñas complejas.
        /// </summary>
        internal static string PwGenComplex {
            get {
                return ResourceManager.GetString("PwGenComplex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generador de contraseñas criptográficas.
        /// </summary>
        internal static string PwGenCrypto {
            get {
                return ResourceManager.GetString("PwGenCrypto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generador de número de PIN.
        /// </summary>
        internal static string PwGenPin {
            get {
                return ResourceManager.GetString("PwGenPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generador de contraseñas seguras.
        /// </summary>
        internal static string PwGenSafe {
            get {
                return ResourceManager.GetString("PwGenSafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Caracteres latinos.
        /// </summary>
        internal static string PwLatinEvalRule {
            get {
                return ResourceManager.GetString("PwLatinEvalRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Minúsculas.
        /// </summary>
        internal static string PwLcaseEvalRule {
            get {
                return ResourceManager.GetString("PwLcaseEvalRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Longitud de contraseña.
        /// </summary>
        internal static string PwLenghtEvalRule {
            get {
                return ResourceManager.GetString("PwLenghtEvalRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esta regla evalúa la longitud de la contraseña, para asegurarse que contenga de {0} a {1} caracteres..
        /// </summary>
        internal static string PwLenghtEvalRule2 {
            get {
                return ResourceManager.GetString("PwLenghtEvalRule2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se necesita una contraseña..
        /// </summary>
        internal static string PwNeeded {
            get {
                return ResourceManager.GetString("PwNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay reglas activas..
        /// </summary>
        internal static string PwNoActiveRules {
            get {
                return ResourceManager.GetString("PwNoActiveRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Números.
        /// </summary>
        internal static string PwNumbersEvalRule {
            get {
                return ResourceManager.GetString("PwNumbersEvalRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Otros símbolos.
        /// </summary>
        internal static string PwOtherSymbsEvalRule {
            get {
                return ResourceManager.GetString("PwOtherSymbsEvalRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Otros caracteres Unicode.
        /// </summary>
        internal static string PwOtherUTFEvalRule {
            get {
                return ResourceManager.GetString("PwOtherUTFEvalRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Símbolos.
        /// </summary>
        internal static string PwSymbolsEvalRule {
            get {
                return ResourceManager.GetString("PwSymbolsEvalRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña es demasiado larga..
        /// </summary>
        internal static string PwTooLong {
            get {
                return ResourceManager.GetString("PwTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña es demasiado corta..
        /// </summary>
        internal static string PwTooShort {
            get {
                return ResourceManager.GetString("PwTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mayúsculas.
        /// </summary>
        internal static string PwUcaseEvalRule {
            get {
                return ResourceManager.GetString("PwUcaseEvalRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña segura.
        /// </summary>
        internal static string SafePw {
            get {
                return ResourceManager.GetString("SafePw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esta regla evalúa que la contraseña contenga {0}.
        /// </summary>
        internal static string xBuilder {
            get {
                return ResourceManager.GetString("xBuilder", resourceCulture);
            }
        }
    }
}
