//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheXDS.MCART.ExceptionLib.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheXDS.MCART.ExceptionLib.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EL uso de la clase especificada es peligroso..
        /// </summary>
        internal static string ClassIsDangerous {
            get {
                return ResourceManager.GetString("ClassIsDangerous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El uso de la clase &apos;{0}&apos; es peligroso..
        /// </summary>
        internal static string ClassXIsDangerous {
            get {
                return ResourceManager.GetString("ClassXIsDangerous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La conexión se ha cerrado inesperadamente..
        /// </summary>
        internal static string ConnClosed {
            get {
                return ResourceManager.GetString("ConnClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se han recibido datos corruptos..
        /// </summary>
        internal static string CorruptDataReceived {
            get {
                return ResourceManager.GetString("CorruptDataReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No fue posible establecer una conexión..
        /// </summary>
        internal static string CouldntConnect {
            get {
                return ResourceManager.GetString("CouldntConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No fue posible conectarse a &apos;{0}&apos;..
        /// </summary>
        internal static string CouldntConnectTo {
            get {
                return ResourceManager.GetString("CouldntConnectTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se han encontrado los datos..
        /// </summary>
        internal static string DataNotFound {
            get {
                return ResourceManager.GetString("DataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La característica no está disponible..
        /// </summary>
        internal static string FeatureNotAvailable {
            get {
                return ResourceManager.GetString("FeatureNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos insuficientes..
        /// </summary>
        internal static string InsufficientData {
            get {
                return ResourceManager.GetString("InsufficientData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Base de datos inválida..
        /// </summary>
        internal static string InvalidDB {
            get {
                return ResourceManager.GetString("InvalidDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El método {0} ha devuelto un valor inválido en este contexto..
        /// </summary>
        internal static string InvalidFuncReturnValue {
            get {
                return ResourceManager.GetString("InvalidFuncReturnValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El método {0} ha devuelto {1}, el cual no es un valor válido en este contexto..
        /// </summary>
        internal static string InvalidFuncXReturnValue {
            get {
                return ResourceManager.GetString("InvalidFuncXReturnValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El método no tiene una firma válida..
        /// </summary>
        internal static string InvalidMethodSignature {
            get {
                return ResourceManager.GetString("InvalidMethodSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EL método &apos;{0}&apos; no tiene una firma válida..
        /// </summary>
        internal static string InvalidMethodXSignature {
            get {
                return ResourceManager.GetString("InvalidMethodXSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña inválida..
        /// </summary>
        internal static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El método ha devuelto un valor inválido en este contexto..
        /// </summary>
        internal static string InvalidReturnValue {
            get {
                return ResourceManager.GetString("InvalidReturnValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La base de datos &apos;{0}&apos; no es válida..
        /// </summary>
        internal static string InvalidXDB {
            get {
                return ResourceManager.GetString("InvalidXDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La llamada al método especificado es peligrosa..
        /// </summary>
        internal static string MethodIsDangerous {
            get {
                return ResourceManager.GetString("MethodIsDangerous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La llamada al método &apos;{0}&apos; es peligrosa..
        /// </summary>
        internal static string MethodXIsDangerous {
            get {
                return ResourceManager.GetString("MethodXIsDangerous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha encontrado un argumento necesario..
        /// </summary>
        internal static string MissingArg {
            get {
                return ResourceManager.GetString("MissingArg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha encontrado el argumento {0}..
        /// </summary>
        internal static string MissingXArg {
            get {
                return ResourceManager.GetString("MissingXArg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La base de datos no pertenece a esta aplicación..
        /// </summary>
        internal static string NotMyDatabase {
            get {
                return ResourceManager.GetString("NotMyDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La operación ha fallado..
        /// </summary>
        internal static string OperationFailed {
            get {
                return ResourceManager.GetString("OperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Una operación dentro del método &apos;{0}&apos; ha fallado..
        /// </summary>
        internal static string OperationXFailed {
            get {
                return ResourceManager.GetString("OperationXFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha encontrado el servidor..
        /// </summary>
        internal static string ServerNotFound {
            get {
                return ResourceManager.GetString("ServerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se han especificado muy pocos argumentos..
        /// </summary>
        internal static string TooFewArguments {
            get {
                return ResourceManager.GetString("TooFewArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se han especificado demasiados argumentos..
        /// </summary>
        internal static string TooManyArguments {
            get {
                return ResourceManager.GetString("TooManyArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Uid ya existe..
        /// </summary>
        internal static string UidAlreadyExists {
            get {
                return ResourceManager.GetString("UidAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Uid &apos;{0}&apos; ya existe..
        /// </summary>
        internal static string UidXAlreadyExists {
            get {
                return ResourceManager.GetString("UidXAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo desconocido..
        /// </summary>
        internal static string UnknownType {
            get {
                return ResourceManager.GetString("UnknownType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El objeto no puede ser utilizado..
        /// </summary>
        internal static string UnusableObject {
            get {
                return ResourceManager.GetString("UnusableObject", resourceCulture);
            }
        }
    }
}
