/*
TypeBooleanConverter.cs

This file is part of Morgan's CLR Advanced Runtime (MCART)

Author(s):
     César Andrés Morgan <xds_xps_ivx@hotmail.com>

Released under the MIT License (MIT)
Copyright © 2011 - 2026 César Andrés Morgan

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
of the Software, and to permit persons to whom the Software is furnished to do
so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

using System.Globalization;
using TheXDS.MCART.Resources;

namespace TheXDS.MCART.ValueConverters;

/// <summary>
/// Determines whether an object is an instance of the supplied type or a derived class,
/// and returns <see langword="true"/> if it is.
/// </summary>
public sealed partial class TypeBooleanConverter
{
    /// <summary>
    /// Determines whether an object is an instance of the supplied type or a derived class.
    /// </summary>
    /// <param name="value">
    /// Value generated by the binding source.
    /// </param>
    /// <param name="targetType">
    /// The type of the target binding property.
    /// </param>
    /// <param name="parameter">
    /// Converter parameter to use.
    /// </param>
    /// <param name="culture">
    /// Culture reference to use in the converter.
    /// </param>
    /// <returns>
    /// <see langword="true"/> if the object is an instance of the supplied type or
    /// a derived class; <see langword="false"/> otherwise.
    /// </returns>
    public object Convert(object? value, Type targetType, object? parameter, CultureInfo culture)
    {
        if (parameter is not Type t) throw Errors.InvalidValue(nameof(parameter));
        return t.IsAssignableFrom(value?.GetType());
    }

    /// <summary>
    /// Executes a reverse conversion.
    /// </summary>
    /// <param name="value">
    /// Object to convert.
    /// </param>
    /// <param name="targetType">
    /// Target type.
    /// </param>
    /// <param name="parameter">
    /// Custom parameters used for the conversion.
    /// </param>
    /// <param name="culture">
    /// <see cref="CultureInfo"/> used for the conversion.
    /// </param>
    /// <returns>
    /// This method always throws an <see cref="InvalidOperationException"/>.
    /// </returns>
    /// <exception cref="InvalidOperationException">
    /// This method always throws this exception when called.
    /// </exception>
    public object ConvertBack(object? value, Type targetType, object? parameter, CultureInfo culture)
    {
        throw new InvalidOperationException();
    }
}
