//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheXDS.MCART.Wpf.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheXDS.MCART.Resources.Strings.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acerca de MCART....
        /// </summary>
        public static string AboutMCART {
            get {
                return ResourceManager.GetString("AboutMCART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Abstracto.
        /// </summary>
        public static string Abstract {
            get {
                return ResourceManager.GetString("Abstract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipos base.
        /// </summary>
        public static string BaseTypes {
            get {
                return ResourceManager.GetString("BaseTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string BtnCancel {
            get {
                return ResourceManager.GetString("BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Borrar.
        /// </summary>
        public static string BtnDel {
            get {
                return ResourceManager.GetString("BtnDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        public static string BtnEdit {
            get {
                return ResourceManager.GetString("BtnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo.
        /// </summary>
        public static string BtnNew {
            get {
                return ResourceManager.GetString("BtnNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        public static string BtnSave {
            get {
                return ResourceManager.GetString("BtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ensamblado de declaración.
        /// </summary>
        public static string DeclaringAssembly {
            get {
                return ResourceManager.GetString("DeclaringAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor predeterminado.
        /// </summary>
        public static string DefaultValue {
            get {
                return ResourceManager.GetString("DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo dinámico.
        /// </summary>
        public static string DynamicType {
            get {
                return ResourceManager.GetString("DynamicType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Argumentos de tipo genérico.
        /// </summary>
        public static string GenericArgs {
            get {
                return ResourceManager.GetString("GenericArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo genérico.
        /// </summary>
        public static string GenericType {
            get {
                return ResourceManager.GetString("GenericType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Instanciable.
        /// </summary>
        public static string Instantiable {
            get {
                return ResourceManager.GetString("Instantiable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Interfaces.
        /// </summary>
        public static string Interfaces {
            get {
                return ResourceManager.GetString("Interfaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de referencia (Clase).
        /// </summary>
        public static string IsClass {
            get {
                return ResourceManager.GetString("IsClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de enumeración.
        /// </summary>
        public static string IsEnum {
            get {
                return ResourceManager.GetString("IsEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo genérico construido.
        /// </summary>
        public static string IsGenericBuilt {
            get {
                return ResourceManager.GetString("IsGenericBuilt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Interfaz.
        /// </summary>
        public static string IsInterface {
            get {
                return ResourceManager.GetString("IsInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo primitivo.
        /// </summary>
        public static string IsPrimitive {
            get {
                return ResourceManager.GetString("IsPrimitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo sellado.
        /// </summary>
        public static string IsSealed {
            get {
                return ResourceManager.GetString("IsSealed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo estático.
        /// </summary>
        public static string IsStatic {
            get {
                return ResourceManager.GetString("IsStatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de valor.
        /// </summary>
        public static string IsValueType {
            get {
                return ResourceManager.GetString("IsValueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Espacio de nombres.
        /// </summary>
        public static string Namespace {
            get {
                return ResourceManager.GetString("Namespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva instancia.
        /// </summary>
        public static string NewInstance {
            get {
                return ResourceManager.GetString("NewInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo registro.
        /// </summary>
        public static string NewReg {
            get {
                return ResourceManager.GetString("NewReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  de .
        /// </summary>
        public static string Of {
            get {
                return ResourceManager.GetString("Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Propiedades.
        /// </summary>
        public static string Properties {
            get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Miembros públicos.
        /// </summary>
        public static string PublicMembers {
            get {
                return ResourceManager.GetString("PublicMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar....
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver licencias de terceros....
        /// </summary>
        public static string See3rdPartyLicenses {
            get {
                return ResourceManager.GetString("See3rdPartyLicenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver licencia....
        /// </summary>
        public static string SeeLicense {
            get {
                return ResourceManager.GetString("SeeLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo serializable.
        /// </summary>
        public static string Serializable {
            get {
                return ResourceManager.GetString("Serializable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre del tipo.
        /// </summary>
        public static string TypeName {
            get {
                return ResourceManager.GetString("TypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Versión.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} de {1}.
        /// </summary>
        public static string XOfY {
            get {
                return ResourceManager.GetString("XOfY", resourceCulture);
            }
        }
    }
}
