//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheXDS.MCART.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TypeFactoryStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TypeFactoryStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheXDS.MCART.Resources.TypeFactoryStrings", typeof(TypeFactoryStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede definir una llamada para la carga de argumentos en este contexto. Elimine la llamada, o especifique los parámetros del constructor base a llamar..
        /// </summary>
        internal static string ErrCallCtorCallback {
            get {
                return ResourceManager.GetString("ErrCallCtorCallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible combinar los tipos especificados debido a conflictos entre los miembros a incluir en el tipo resultante..
        /// </summary>
        internal static string ErrCannotJoinTypes {
            get {
                return ResourceManager.GetString("ErrCannotJoinTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se esperaba una definición de método desde una interfaz..
        /// </summary>
        internal static string ErrIFaceMethodExpected {
            get {
                return ResourceManager.GetString("ErrIFaceMethodExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tipo no implementa la interfaz &apos;{0}&apos;..
        /// </summary>
        internal static string ErrIfaceNotImpl {
            get {
                return ResourceManager.GetString("ErrIfaceNotImpl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La propiedad no contiene accesor de lectura..
        /// </summary>
        internal static string ErrPropCannotBeRead {
            get {
                return ResourceManager.GetString("ErrPropCannotBeRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya se ha definido un campo de almacenamiento para la propiedad..
        /// </summary>
        internal static string ErrPropFieldAlreadyDefined {
            get {
                return ResourceManager.GetString("ErrPropFieldAlreadyDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya se ha definido un Getter para la propiedad..
        /// </summary>
        internal static string ErrPropGetterAlreadyDefined {
            get {
                return ResourceManager.GetString("ErrPropGetterAlreadyDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya se ha definido un Setter para la propiedad..
        /// </summary>
        internal static string ErrPropSetterAlreadyDefined {
            get {
                return ResourceManager.GetString("ErrPropSetterAlreadyDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los tipos del TypeBuilder especificado con tipo base {0} y el tipo base explícito &apos;{1}&apos; no coinciden. Se requiere un tipo que herede/implemente {1}..
        /// </summary>
        internal static string TypeBuilderTypeMismatch {
            get {
                return ResourceManager.GetString("TypeBuilderTypeMismatch", resourceCulture);
            }
        }
    }
}
