name: "Build MCART"
on:
  push:
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
    branches-ignore:
      - 'docs*'
    tags-ignore:
      - '*'
jobs:
  build:
    runs-on: windows-latest
    env:
      Solution_Name: src/MCART.sln
      Configuration: Debug
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build and test MCART
      run: dotnet test $env:Solution_Name --configuration=$env:Configuration
    - name: Create NuGet Packages
      run: dotnet pack $env:Solution_Name --configuration=$env:Configuration --version-suffix=$env:GITHUB_SHA --include-source -p:RepositoryBranch=${{ github.ref }} -p:ContinuousIntegrationBuild=true
    - uses: actions/upload-artifact@v2
      with:
        name: MCART-nuget-packages
        path: Build/Bin/**/*.nupkg
