name: "Build MCART"
on:
  push:
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
    branches-ignore:
      - 'docs*'
    tags-ignore:
      - '*'
jobs:
  build:
    runs-on: windows-latest
    env:
      Solution_Name: src/MCART.slnx
      Configuration: Debug
    steps:
    - name: Checkout
      uses: actions/checkout@v6
    - name: Install .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 8.0.x
    - name: Build MCART
      run: dotnet build $env:Solution_Name --configuration=$env:Configuration
    - name: Test MCART
      run: dotnet test $env:Solution_Name --no-build --collect:"XPlat Code Coverage" --results-directory .\Build\tests -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura
    - name: Upload code coverage to Codecov
      uses: codecov/codecov-action@v6
      with:
        files: ./Build/tests/*/coverage.cobertura.xml
        fail_ci_if_error: false
    - name: Create NuGet Packages
      run: dotnet pack $env:Solution_Name --configuration=$env:Configuration --version-suffix=$env:GITHUB_SHA --include-source -p:RepositoryBranch=${{ github.ref }} -p:RepositoryCommit=${{ github.sha }}
    - uses: actions/upload-artifact@v7
      with:
        name: MCART-nuget-packages
        path: Build/bin/**/*.nupkg